name: heyya
version: 1.0.0+10
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.4
  get: 4.6.5
  getwidget: ^3.0.1
  device_info_plus: 4.0.0
  cached_network_image: ^3.2.1
  dio: ^4.0.6
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1
  get_storage: ^2.0.3
  tim_ui_kit:
    path: vendor/im
  uuid: ^3.0.6
  extended_image: ^6.2.1
  google_sign_in: ^5.4.2
  sign_in_with_apple: ^4.2.0
  firebase_auth: ^4.1.3
  lottie: ^1.4.2
  wechat_camera_picker: ^3.5.0+1
  wechat_assets_picker: ^7.3.4
  provider: ^6.0.3
  video_thumbnail: ^0.4.6
  video_player: ^2.4.7
  swipable_stack: ^2.0.0
  percent_indicator: ^4.2.2
  align_positioned: ^3.0.0
  ff_annotation_route_library: ^3.0.0
  flutter_easyrefresh: ^2.2.2
  bot_toast: ^4.0.3
  intl: ^0.17.0
  flutter_native_splash: ^2.2.9
  focus_detector: ^2.0.1
  flutter_keychain: ^2.2.1
  flutter_image_compress: ^1.1.3
  path: ^1.8.1
  permission_handler: ^9.2.0    
  visibility_detector: ^0.2.2
  #社交平台分享插件
  social_share: ^2.2.1
  # 本地分享
  share_plus: ^4.1.0
  ffmpeg_kit_flutter_min_gpl: ^5.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#DDEF00"
  image: assets/images/splash.png

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter_assets:
  assets_path:
    - images/launcher_logo.png
    - images/a_dot_burr.jpeg
    - assets/images/profile/
    - assets/images/signin/
    - assets/images/assets_picker/
    - assets/images/report/
    - assets/images/common/
    - assets/images/moment/
    - assets/images/placeholder/
    - assets/video/
    - assets/images/spark/
    - assets/images/tabbar/
    - assets/lottie/
  output_path: lib/app/core/assets/

flutter:
  uses-material-design: true

  assets:
    - assets/images/profile/
    - assets/images/signin/
    - assets/images/assets_picker/
    - assets/images/report/
    - assets/images/common/
    - assets/images/moment/
    - assets/images/placeholder/
    - assets/video/
    - assets/images/spark/
    - assets/images/tabbar/
    - assets/lottie/
  fonts:
    - family: SinhalaMN
      fonts:
        - asset: assets/fonts/SinhalaMN.ttf
          weight: 400
          style: normal
    - family: SinhalaMN-Bold
      fonts:
        - asset: assets/fonts/SinhalaMN-Bold.ttf
          weight: 700
          style: normal