// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCwWFcUmWw_SJWs2NaGftO4knbLh-UW9s',
    appId: '1:1034381393042:web:7864a3af489fa29620ba4b',
    messagingSenderId: '1034381393042',
    projectId: 'heyya-99ace',
    authDomain: 'heyya-99ace.firebaseapp.com',
    storageBucket: 'heyya-99ace.appspot.com',
    measurementId: 'G-SS4B29LQG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAvMZMZHOG98sZJl27HT6ElMiXHaoDe1Y',
    appId: '1:1034381393042:android:17e0636831a5762f20ba4b',
    messagingSenderId: '1034381393042',
    projectId: 'heyya-99ace',
    storageBucket: 'heyya-99ace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6MrdERmhZahfkPYDerNN1lP6lvpFxZug',
    appId: '1:1034381393042:ios:d1f56f4eaa93676c20ba4b',
    messagingSenderId: '1034381393042',
    projectId: 'heyya-99ace',
    storageBucket: 'heyya-99ace.appspot.com',
    androidClientId: '1034381393042-7uj381qvsmkiaa7jgk793h0df63uq4vu.apps.googleusercontent.com',
    iosClientId: '1034381393042-rb2nl2esfr2lduboad1grehdvmojs6li.apps.googleusercontent.com',
    iosBundleId: 'com.heyyateam.heyya.101',
  );
}
